version: "3.9"

services:
  db:
    build:
      context: .
    image: postgres:16
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: bluen
      POSTGRES_DB: deal_engine
      POSTGRES_PASSWORD: admin
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./challenge_dataset.csv:/app/challenge_dataset.csv

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    links:
      - db:db

#volumes:
#  data: